export const paths = {
  index: "/",
  catalogs: "/catalogs",
  //  catalogs: '/',
  settings: "/settings",
  profile: "/profile",
  user_profile_edit: "/user_profile_edit",
  auth: "/auth",
  register: "/register",
  //register: '/',
  catalog: "/catalogs/:id",
  catalogAds: "/catalogs/:id/ads/:idAds",
  createAds: "/create",
  policy: "/policy",
  error: "/*",
  typeCatalog: "/type-catalog",
  passwordRecovery: "/password-recovery",
  newPassword: "...",
  forgetPassword: "/password-forget",
  registryActivate: "/registry-activate",
  chat: '/chat',
  moderation: '/moderation' // Added path for moderation mainpage
};
