export const paths = {
  index: "/",
  catalogs: "/catalogs",
  //  catalogs: '/',
  settings: "/settings",
  profile: "/profile",
  passwordChange: '/password-change',
  favorites: "/favorites",
  user_profile_edit: "/user_profile_edit",
  auth: "/auth",
  register: "/register",
  //register: '/',
  confirmEmail: "/confirm-email",
  catalog: "/catalogs/:id",
  catalogService: "/catalogs/:id/service/:idService",
  adPage: "/ad/:idAds",
  servicePage: "/service/:idService",
  createAds: "/create",
  policy: "/policy",
  error: "/*",
  typeCatalog: "/type-catalog",
  passwordRecovery: "/password-recovery",
  newPassword: "...",
  forgetPassword: "/password-forget",
  registryActivate: "/registry-activate",
  chat: `/chat/:objectType/:object_id/:buyer_id`,
  moderation: "/moderation", // Added path for moderation mainpage
  myAds: '/my-ads',
  myReviews: "my-reviews"
};
